### ISSUE TITLE
Uwagi

### ISSUE THREAD

**Issue by MarcinCiura** [maciekspolnik/Projekt_Okrety#1]
1. Wydaje mi się, że `.gitignore.txt` nie zadziała. Ma być `.gitignore`.
2. Moduły `sys` i `socket` dostał Pan z Pythonem. Zagadka: co się stanie, kiedy Pan uruchomi `pip install -r requirements.txt`?
3. Pliki dla obu graczy są bardzo podobne. Wydzielić część wspólną np. do `gracz.py` i ją importować w obu.
4. Zdecydować się na jeden język (`get_tile`, `text_rect`, `check_statek` itp.?).
5. `kier` (kolor w kartach), `mess` (balagan), `kolej_przec`? Skróty i jednoliterowce, jak `s` w `main()` i inne są nieczytelne (2. rozdział Poradnika).
6. Inicjalizację `pygame` przenieść do `main()` (3. rozdział).
7. Zamiast zmiennych globalnych `p1` i `p2` (o złych nazwch) zrobić klasę np. `Statki`, w której konstruktorze przypiszą się atrybuty `self.nasza_plansza` i `self.wroga_plansza` lub o podobnych nazwach (2. rozdział).
8. Funkcja `main()` jest za długa. Z części w rodzaju ustawiania statków, łączenia z przeciwnikiem, pętli rozgrywki zrobić osobne funkcje albo metody klasy `Statki`. Co takie samo — do `gracz.py`.
9. Lepiej zrobić np. taką klasę:
```python
class Kafelek:
    def __init__(self, jest_statkiem):
        self.jest_statkiem = jest_statkiem
        self.jest_odsłonięty = False
        self.jest_ostrzelany = False
```
i dwuwymiarowe `self.nasza_plansza` i `self.wroga_plansza` o elementach typu `Kafelek`.
10. Nie trzeba sprawdzać `if spam is True:`. Wystarczy `if spam:`.
11. Zrobić funkcje do kodowania i dekodowania komunikatów.

**Comment by maciekspolnik** [comment]
Poprawki zgodne z uwagami dodane

**Comment by MarcinCiura** [comment]
Dziękuję za poprawki. Kolejna porcja uwag.

1. [Nie rozumiem `if_`](https://github.com/maciekspolnik/Projekt_Okrety/blob/33fb4716addad883a8a23fbe5c9444d1d695ab63/battleship.py#L15). Lepsze `is_`.
2. [`DIMENSION`](https://github.com/maciekspolnik/Projekt_Okrety/blob/33fb4716addad883a8a23fbe5c9444d1d695ab63/battleship.py#L38).
3. [Tak nie wolno](https://github.com/maciekspolnik/Projekt_Okrety/blob/33fb4716addad883a8a23fbe5c9444d1d695ab63/battleship.py#L48). Licznik pętli z 2. rozdziału oznacza zmienną całkowitą, a nie cokolwiek, po czym przebiega pętla. Zmienić `j` np. na `row`.
4. [`i` też złe](https://github.com/maciekspolnik/Projekt_Okrety/blob/33fb4716addad883a8a23fbe5c9444d1d695ab63/battleship.py#L50). Po to chyba Pan sobie zrobił `Tile.reset_tile()`, prawda?
5. [Wolałbym `(my_constants.TILE_SPACE + my_constants.TILE_SIZE)`](https://github.com/maciekspolnik/Projekt_Okrety/blob/33fb4716addad883a8a23fbe5c9444d1d695ab63/battleship.py#L66)
6. [Tutaj](https://github.com/maciekspolnik/Projekt_Okrety/blob/33fb4716addad883a8a23fbe5c9444d1d695ab63/battleship.py#L88) napisać tak:
```python
if directory == my_constants.POZIOM:
    coordinate_i, coordinate_j = y_ship, x_ship
else:
    coordinate_i, coordinate_j = x_ship, y_ship
```
7. [Zbędne](https://github.com/maciekspolnik/Projekt_Okrety/blob/33fb4716addad883a8a23fbe5c9444d1d695ab63/battleship.py#L104).
8. [Stałą 10 nazwać](https://github.com/maciekspolnik/Projekt_Okrety/blob/33fb4716addad883a8a23fbe5c9444d1d695ab63/battleship.py#L130).
9. [Wolałbym `y_coord` i `x_coord` przekazywane osobno](https://github.com/maciekspolnik/Projekt_Okrety/blob/33fb4716addad883a8a23fbe5c9444d1d695ab63/battleship.py#L157).
10. [Użyć nawiasów](https://github.com/maciekspolnik/Projekt_Okrety/blob/33fb4716addad883a8a23fbe5c9444d1d695ab63/battleship.py#L161) (ostatni punkt 2. rozdziału).
11. [`if event_type in (pygame.QUIT, pygame.KEY_DOWN):`](https://github.com/maciekspolnik/Projekt_Okrety/blob/33fb4716addad883a8a23fbe5c9444d1d695ab63/battleship.py#L232).
12. Jak w 3. i 4.
13. [Z 3/4 tego](https://github.com/maciekspolnik/Projekt_Okrety/blob/33fb4716addad883a8a23fbe5c9444d1d695ab63/battleship.py#L410) zrobić metodę Kafelka.
14. [Z tego też](https://github.com/maciekspolnik/Projekt_Okrety/blob/33fb4716addad883a8a23fbe5c9444d1d695ab63/battleship.py#L424).
15. Nadal połowa obu funkcji `main()` jest identyczna. Wyjąć do funkcji w `battleship.py`.

**Comment by maciekspolnik** [comment]
Kolejna porcja poprawek wprowadzona.

**Comment by MarcinCiura** [comment]
Nieźle.

1. [`battleship` < `my_constants`](https://github.com/maciekspolnik/Projekt_Okrety/blob/b6c8cbb4088fee1fa80e8d3a3c7e11e43a18fa88/player_1.py#L8).
2. Zamiast `LIGHT_BLUE`, `LIGHT_RED` itp. lepiej `SEA_COLOR`, `SHIP_COLOR` itp., co nie doprowadzi do absurdu, jeśli kiedyś Pan zechce mieć zielone okręty.
3. [`MESSAGE`](https://github.com/maciekspolnik/Projekt_Okrety/blob/b6c8cbb4088fee1fa80e8d3a3c7e11e43a18fa88/my_constants.py#L44).
4. [Po prostu `return f'...'`](https://github.com/maciekspolnik/Projekt_Okrety/blob/b6c8cbb4088fee1fa80e8d3a3c7e11e43a18fa88/battleship.py#L36).
5. Wolałbym całą [tę funkcję](https://github.com/maciekspolnik/Projekt_Okrety/blob/b6c8cbb4088fee1fa80e8d3a3c7e11e43a18fa88/battleship.py#L443) jako `update_tile()` w `Tile`.
6. Opcjonalnie: używać samogłosek w `/imgs`.

**Comment by maciekspolnik** [comment]
Poprawki uwzględnione.

**Comment by MarcinCiura** [comment]
LGTM. Gratuluję, jest Pan drugi.
Po polsku [to są](https://github.com/maciekspolnik/Projekt_Okrety/blob/4474a4393fcba05487ef5b052ddc130701d4a630/my_constants.py#L9) współrzędne.

**Comment by MarcinCiura** [comment]
Aaa. Za szybko. Brakuje testów.

**Comment by maciekspolnik** [comment]
O testach oczywiście pamiętałem. Stworzyłem kilka testów. Od razu spytam, czy dobrze zrozumiałem, na czym mają polegać i czy ma być ich jeszcze więcej, czy tyle wystarczy.

**Comment by MarcinCiura** [comment]
1. Więcej testów nie trzeba.
2. Zmienić nazwę pliku na `battleship_test.py` (3. rozdział).
3. Wszelką losowość pousuwać. Testy mają być deterministyczne. Zamiast tego sprawdzać w osobnych metodach z zakodowanymi na sztywno danymi wejściowymi, czy wynik się zgadza z oczekiwaniami. Więc wszystkie metody, w których na dwoje babka wróżyła, się Panu rozdwoją.
4. Z docstringami Pan przesadził. Nie są ani potrzebne, ani zalecane, oprócz tego na górze (3. rozdział). Zamiast nich lepsze są mówiące nazwy metod, np. `test_update_tile_returns_list`, `test_check_ship_of_length_3_hit`, `test_check_ship_of_length_3_miss`, bo są wyświetlane przy ewentualnych niepowodzeniach (polecam próbnie popsuć jakiś test i zobaczyć, co się stanie).
5. `TestGameGrid` na `GameGridTest`, `VariousTests` na `MessageTest`.

**Comment by maciekspolnik** [comment]
Poprawki wprowadzone.

**Comment by MarcinCiura** [comment]
1. [Tutaj](https://github.com/maciekspolnik/Projekt_Okrety/blob/ac8df72946edd87a26d6124ae1ed873edbc8b558/battleship_test.py#L19) rozbić na dwa, bo teraz jest wróżąca babka (`True` and `False` == `False`).
2. [Tu](https://github.com/maciekspolnik/Projekt_Okrety/blob/ac8df72946edd87a26d6124ae1ed873edbc8b558/battleship_test.py#L40) też rozbić na trzy, żeby w razie czego było widać, co padło.
3. [Tu](https://github.com/maciekspolnik/Projekt_Okrety/blob/ac8df72946edd87a26d6124ae1ed873edbc8b558/battleship_test.py#L45) i [tu](https://github.com/maciekspolnik/Projekt_Okrety/blob/ac8df72946edd87a26d6124ae1ed873edbc8b558/battleship_test.py#L75) lepiej by było po testowaniu typu dodać `assertEqual()` z oczekiwaną zawartością (i zmienić nazwę metody).
4. Podobnie [tu](https://github.com/maciekspolnik/Projekt_Okrety/blob/ac8df72946edd87a26d6124ae1ed873edbc8b558/battleship_test.py#L94) porównać z oczekiwaniami, co samo załatwi sprawdzenie długości.
5. Podobnie [tu](https://github.com/maciekspolnik/Projekt_Okrety/blob/ac8df72946edd87a26d6124ae1ed873edbc8b558/battleship_test.py#L98) porównać całość, a nie kawałek.

**Comment by maciekspolnik** [comment]
Nowe poprawki dodane.

**Comment by MarcinCiura** [comment]
Ostatnia (?) zmiana: wszędzie tam, gdzie [`result`](https://github.com/maciekspolnik/Projekt_Okrety/blob/b39bd91e7d419d4baa4569daa2f310f11abcad34/battleship_test.py#L19) jest krótki i używany raz, połączyć dwa wiersze w jeden (wstawić `self.tile.is_revealed` do `self.assertFalse()`).

**Comment by maciekspolnik** [comment]
Zrobione.

**Comment by MarcinCiura** [comment]
Proszę jeszcze sprawdzić, czy `.assertEqual((0, 0), [0, 0])` przechodzi (myślę, że nie). Jeśli nie, to powyrzucać `.isInstance()` jako nadmiarowe i tym razem na pewno poprawić nazwy metod.

**Comment by maciekspolnik** [comment]
Poprawione.

**Comment by MarcinCiura** [comment]
LGTM. Drugi!
